name: Charmed Vision Media
favicon: null
layout_spectrum: 0.9882864160463214
typography_spectrum: 0.8582558315247297
title: Charmed Vision Media
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.44455534871667624
  lightness: 0.4647056432440877
  saturation: 0.5039537462871522
  rhythmicContrast: 0.3828820511698723
purpose: []
